# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================

test-settings:
  user-workflow:
    workflow-name: "workflow-observer-test"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.test.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "workflow-observer-staging"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.staging.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "workflow-observer"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.production.json"
    secrets-path: "../secrets.yaml"
